services:
    - docker

install:
    - docker build -t cadl . 

script:
    - docker run -it -v /$(pwd)/session_1:/notebooks cadl py.test
    - docker run -it -v /$(pwd)/session_2:/notebooks cadl py.test
    - docker run -it -v /$(pwd)/session_3:/notebooks cadl py.test
    - docker run -it -v /$(pwd)/session_4:/notebooks cadl py.test
    - docker run -it -v /$(pwd)/session_5:/notebooks cadl py.test

after_failure:
    - docker logs cadl
